"""Mosquitto password file and ACL management for tenant isolation."""

import asyncio
import logging
import re
from pathlib import Path

from .. import config

logger = logging.getLogger(__name__)

_lock = asyncio.Lock()


def _passwd_path() -> Path:
    return config.SECURITY_INFRA_DIR / "mosquitto_passwd"


def _acl_path() -> Path:
    return config.SECURITY_INFRA_DIR / "mosquitto_acl"


def _conf_path() -> Path:
    return config.SECURITY_INFRA_DIR / "mosquitto.conf"


def is_bootstrapped() -> bool:
    """Check if Mosquitto config files have been generated."""
    return _passwd_path().exists() and _acl_path().exists() and _conf_path().exists()


async def add_user(username: str, password: str) -> None:
    """Add or update a user in the Mosquitto password file.

    Uses ``mosquitto_passwd -b`` to hash the password. Creates the file
    with ``-c`` on first call.
    """
    async with _lock:
        passwd = _passwd_path()
        flag = "-c" if not passwd.exists() else "-b"
        # -c creates (overwrites) the file; -b uses batch mode.
        # When creating we still need -b for batch (non-interactive).
        args = ["mosquitto_passwd", "-b"]
        if not passwd.exists():
            args = ["mosquitto_passwd", "-c", "-b"]
        args += [str(passwd), username, password]

        proc = await asyncio.create_subprocess_exec(
            *args,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=10)
        if proc.returncode != 0:
            msg = stderr.decode().strip() or stdout.decode().strip()
            raise RuntimeError(f"mosquitto_passwd failed: {msg}")

        logger.info("Added MQTT user: %s", username)


def generate_config(host: str, port: str = "1883") -> None:
    """Write mosquitto.conf with container-internal paths."""
    conf = _conf_path()
    conf.parent.mkdir(parents=True, exist_ok=True)
    conf.write_text(
        "# Mosquitto configuration \u2014 generated by Device Connect portal\n"
        f"listener {port} 0.0.0.0\n"
        "allow_anonymous false\n"
        "password_file /mosquitto/config/mosquitto_passwd\n"
        "acl_file /mosquitto/config/mosquitto_acl\n"
        "log_type all\n"
        "persistence true\n"
        "persistence_location /mosquitto/data/\n"
    )
    logger.info("Generated Mosquitto config: %s", conf)


def generate_initial_acl(privileged_users: list[str]) -> None:
    """Write the initial ACL file granting privileged users full access."""
    acl = _acl_path()
    acl.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    for name in privileged_users:
        lines += [
            f"# Privileged: {name}",
            f"user {name}",
            "topic readwrite device-connect/#",
            "topic readwrite _reply/#",
            "",
        ]
    acl.write_text("\n".join(lines) + "\n")
    logger.info("Generated initial Mosquitto ACL: %s", acl)


def add_tenant_acl(tenant: str, device_usernames: list[str]) -> None:
    """Append per-device ACL rules for a tenant."""
    acl = _acl_path()
    lines = [f"\n# Tenant: {tenant}"]
    for username in device_usernames:
        lines += [
            f"user {username}",
            f"topic readwrite device-connect/{tenant}/#",
            "topic readwrite _reply/#",
            "",
        ]
    with open(acl, "a") as f:
        f.write("\n".join(lines) + "\n")
    logger.info("Added ACL rules for tenant '%s': %d device(s)", tenant, len(device_usernames))


def add_devices_to_tenant(tenant: str, device_usernames: list[str]) -> None:
    """Add devices to an existing tenant (ACL is additive)."""
    add_tenant_acl(tenant, device_usernames)


def list_tenant_rules() -> dict[str, list[str]]:
    """Parse the ACL file and return {tenant: [username, ...]} for non-privileged users."""
    acl = _acl_path()
    if not acl.exists():
        return {}

    tenants: dict[str, list[str]] = {}
    current_tenant: str | None = None

    for line in acl.read_text().splitlines():
        line = line.strip()
        m = re.match(r"^# Tenant:\s*(.+)$", line)
        if m:
            current_tenant = m.group(1).strip()
            if current_tenant not in tenants:
                tenants[current_tenant] = []
            continue

        if line.startswith("# Privileged:"):
            current_tenant = None
            continue

        if current_tenant and line.startswith("user "):
            username = line[5:].strip()
            tenants[current_tenant].append(username)

    return tenants


def load_acl_text() -> str:
    """Return the raw ACL file content."""
    acl = _acl_path()
    if acl.exists():
        return acl.read_text()
    return ""
